# Generating values for a Pandas Dataframe

### Imports

In [1]:
% matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Random values

In [2]:
np.random.randn(4,5)

array([[-0.5425106 , -0.3822636 ,  0.7905735 , -1.63289721,  0.27310914],
       [-0.41747744, -0.36282364,  0.32662068, -0.21514958,  0.64777063],
       [-1.26280858,  0.52581688,  0.18667944, -0.59296557, -1.20070157],
       [ 1.53048221,  0.1260227 ,  2.22082864,  0.95128111,  1.73193667]])

In [3]:
np.random.randint(10,30,15)

array([17, 17, 18, 22, 12, 26, 28, 14, 12, 16, 10, 23, 17, 13, 13])

### Ranges

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.linspace(0,100,30)

array([   0.        ,    3.44827586,    6.89655172,   10.34482759,
         13.79310345,   17.24137931,   20.68965517,   24.13793103,
         27.5862069 ,   31.03448276,   34.48275862,   37.93103448,
         41.37931034,   44.82758621,   48.27586207,   51.72413793,
         55.17241379,   58.62068966,   62.06896552,   65.51724138,
         68.96551724,   72.4137931 ,   75.86206897,   79.31034483,
         82.75862069,   86.20689655,   89.65517241,   93.10344828,
         96.55172414,  100.        ])